Vagrant.configure(2) do |config|
  config.vm.box = 'windows-2016-amd64-example'

  config.vm.hostname = 'vagrant-example'

  config.vm.provider 'libvirt' do |lv, config|
    lv.memory = 2048
    lv.cpus = 2
    lv.keymap = 'pt'
    # replace the default synced_folder with something that works in cygwin.
    # NB for some reason, this does not work when placed in the base box Vagrantfile.
    config.vm.synced_folder '.', '/vagrant', disabled: true
    config.vm.synced_folder '.', '/cygdrive/c/vagrant', type: 'rsync', rsync__exclude: [
      '.vagrant/',
      '.git/',
      '*.box']
  end

  config.vm.provider 'virtualbox' do |vb|
    # vb.linked_clone = true
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.network :forwarded_port, guest: 3389, host: 33389, id: 'rdp', auto_correct: true
  config.vm.define :'vagrant-example'

  config.vm.communicator = 'winrm'
  config.vm.provision 'shell', path: 'provision.ps1'

end
